### ISSUE TITLE
BUG KeyError pmid with coordinates from fetch_peak_coordinates 

### ISSUE THREAD

**Issue by tomMoral** [neuroquery/neuroquery#11]
I tried to run `examples/training_neuroquery.ipynb`.
As the data is not available anymore on `neuroquery_data`, I used a fresh install from `master`.

With this example, I get a `KeyError: pmid` from this line [neuroquery/img_utils.py#L61](https://github.com/neuroquery/neuroquery/blob/master/neuroquery/img_utils.py#L61):
```python
import pandas as pd

from neuroquery import datasets
from neuroquery.img_utils import coordinates_to_maps

coordinates = pd.read_csv(datasets.fetch_peak_coordinates())
brain_maps, masker = coordinates_to_maps(
    coordinates.iloc[:10], target_affine=(6, 6, 6), fwhm=9.0
)
```

From my understanding, it seems that `pmid` has been changed to `id`?

**Comment by RaphaelMeudec** [comment]
Looking at the first rows of both previous and new files, it seems the data is still the same and the only change is indeed the column renaming

**Comment by jeromedockes** [comment]
thanks for finding this! indeed the column was renamed to harmonize the organization of the data with neurosynth (https://github.com/neuroquery/neuroquery_data/issues/3)
