### ISSUE TITLE
Issues training with different set of studies

### ISSUE THREAD

**Issue by albud187** [neuroquery/neuroquery#13]
Good day.

I am trying to re-train the neuro query model on a subset of the studies in corpus_metadata.csv

My code is on this github repo : https://github.com/albud187/Neuroquery-Work

Basically, I want to be able to retrain the neuroquery model using a subset of the original studies in corpus metadata. For now, I am only interested in using the 30 studies I have identified in "autism_data.csv"  which is in the linked github repo.

I was able to run the original training_neuroquery.ipynb just fine.

I tweaked the code to try to re-train the model so it only uses the studies in "autism_data.csv"
This code is the file "Train Custom Model.ipynb" and is linked here from my github repo: https://github.com/albud187/Neuroquery-Work/blob/main/Train%20Custom%20Model.ipynb

I have an issue when I call the encoder.

It says "Size of label 'j' for operand 1 (6289) does not match previous terms (6308)"

Not sure what is causing it. I'm aware that tfidf is of shape (n,V), where n = number studies, and V = 6308, from vocabulary.
Is there a way to change the shape of tfidf to have V = 6289 or V = (any value I choose)?

**Comment by jeromedockes** [comment]
Hello, as this is about help with usage I answered in the Neurostars post and will close the issue here. Please see https://neurostars.org/t/neuroquery-train-custom-model/20888/2?u=jeromedockes
