### ISSUE TITLE
fetch_peak_coordinates doesn't work because neuroquery data moved

### ISSUE THREAD

**Issue by koudyk** [neuroquery/neuroquery#9]
I think some of the data has moved in [github.com/neuroquery/neuroquery_data](github.com/neuroquery/neuroquery_data), so now the `fetch_peak_coordinates` function in the `datasets` module doesn't work.

**Comment by jeromedockes** [comment]
Thank you! indeed some data has moved: https://github.com/neuroquery/neuroquery_data/issues/3.

do you want to fix that function?

**Comment by koudyk** [comment]
Sure, I'll try to fix it!
